language: node_js
  - 7.10.1
install:
  - npm install -g nodemon
  - npm install -g babel-cli
  - npm install -g cypress
  - npm install -g wait-on
  - npm install
  - ls
  - npm start & cd server; npm start & wait-on "http://localhost:3000/"
script:
  - cypress run
